In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
#Load tree and sequence files
with open('augur_output/flu_seasonal_h3n2_ha_6y_tree.json', 'r') as jsonfile:
    tree_6y = json.load(jsonfile)

with open('augur_output/flu_seasonal_h3n2_ha_6y_sequences.json', 'r') as jsonfile:
    seq_6y = json.load(jsonfile)

In [37]:
#Pull out tree tips from tree.json and HA1 muts (not just tip-specific) from sequences.json
tip_muts = {}

def traverse(branch, seq):
    if 'children' not in branch.keys():
        tip_muts[branch['strain']]=[branch['aa_muts']['HA1'], branch['aa_muts']['HA2'], 
                                    branch['aa_muts']['SigPep'],branch['attr']['num_date'], 
                                    branch['attr']['clade_membership'],seq[str(branch['clade'])]['HA1'], 
                                    (seq[str(branch['clade'])]['HA1']['159'] if '159' in seq[str(branch['clade'])]['HA1'] else 'K')]
    else:
        for child in branch['children']:
            traverse(child, seq)


traverse(tree_6y, seq_6y)

In [38]:
df = pd.DataFrame(tip_muts).T
df.reset_index(inplace=True)
df.rename(columns={'index': 'strain',0: "tip_HA1_muts", 1: "tip_HA2_muts", 2: "tip_SigPep_muts", 
                   3: "date", 4: "clade", 5: 'HA1_muts', 6: 'HA1_160'}, inplace=True)
df['passage'] = np.select((df.strain.str.contains('egg'), df.strain.str.contains('cell')), ('egg', 'cell'))

df.head(20)

,strain,tip_HA1_muts,tip_HA2_muts,tip_SigPep_muts,date,clade,HA1_muts,HA1_160,passage
0,A/AbuDhabi/221/2017-cell,[],[A201T],[],2017.97,A1b/135K,"{u'157': u'N', u'211': u'A', u'159': u'T', u'1...",T,cell
1,A/AbuDhabi/258/2018-cell,[],[],[],2018,A1b/135K,"{u'157': u'N', u'211': u'A', u'159': u'T', u'1...",T,cell
2,A/Acores/SU43/2012-egg,[],[],[A16T],2012.85,unassigned,"{u'229': u'V', u'157': u'N', u'211': u'A', u'1...",K,egg
3,A/Adana/A15/2017-cell,[],[],[],2017.09,A3,"{u'157': u'N', u'156': u'L', u'159': u'T', u'1...",T,cell
4,A/Afghanistan/243/2016-cell,[],[],[],2016.44,3c3.A,"{u'144': u'S', u'157': u'N', u'211': u'A', u'3...",K,cell
5,A/Afghanistan/437/2017,[],[],[],2017.85,A1b/135K,"{u'157': u'N', u'211': u'A', u'159': u'T', u'1...",T,0
6,A/Afghanistan/624/2017,[],[],[],2017.9,A1b/135K,"{u'157': u'N', u'211': u'A', u'159': u'T', u'1...",T,0
7,A/Aichi/116/2013-cell,[],[],[],2013.43,3c3,"{u'144': u'S', u'157': u'N', u'141': u'G', u'3...",K,cell
8,A/Aichi/118/2013-cell,[],[],[],2013.51,3c3,"{u'144': u'S', u'157': u'N', u'141': u'G', u'3...",K,cell
9,A/Aichi/119/2013-cell,[],[],[],2013.83,3c3,"{u'144': u'S', u'157': u'N', u'141': u'G', u'3...",K,cell
10,A/Aichi/126/2013-cell,[],[],[],2013.9,3c3,"{u'144': u'S', u'157': u'N', u'141': u'G', u'3...",K,cell
11,A/Aichi/129/2013-cell,[],[],[],2013.94,3c,"{u'144': u'S', u'157': u'N', u'211': u'A', u'3...",K,cell
12,A/Akita/21/2017-cell,[],[],[],2017.58,A1b/135K,"{u'157': u'N', u'211': u'A', u'158': u'Y', u'1...",K,cell
13,A/Aksaray/4048/2016-cell,[],[A147V],[],2016.16,3c3.A,"{u'144': u'S', u'213': u'T', u'157': u'N', u'2...",K,cell
14,A/Alabama/20/2017,"[S219F, D271N, E325K]",[],[],2017.34,3c3.A,"{u'157': u'N', u'211': u'A', u'158': u'S', u'3...",K,0
15,A/Alaska/13/2014,[],[],[],2014.44,3c3.A,"{u'144': u'S', u'157': u'N', u'141': u'G', u'2...",K,0
16,A/Alaska/14/2013-cell,[A304T],[],[],2013.73,3c3,"{u'144': u'S', u'303': u'T', u'157': u'N', u'1...",K,cell
17,A/Alaska/154/2015-cell,[I300V],[],[],2015.56,3c2.A,"{u'144': u'S', u'310': u'H', u'143': u'S', u'2...",T,cell
18,A/Alaska/157/2015-cell,[],[],[],2015.61,3c2.A,"{u'144': u'S', u'143': u'S', u'222': u'I', u'2...",T,cell
19,A/Alaska/17/2017,[],[],[],2017.47,A2/re,"{u'157': u'N', u'156': u'L', u'159': u'T', u'1...",T,0

In [44]:
#Print genotype percentages for sequences from each passage-type
df.groupby('passage')['HA1_160'].value_counts(normalize=True)

passage  HA1_160
0        T          0.622366
         K          0.371151
         I          0.004862
         A          0.001621
cell     K          0.536164
         T          0.453616
         A          0.003931
         I          0.003931
         R          0.002358
egg      K          0.805243
         T          0.179775
         I          0.007491
         A          0.003745
         R          0.003745
Name: HA1_160, dtype: float64